linters-settings:
  lll:
    line-length: 140
  funlen:
    lines: 100

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - errcheck
    - dupl
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - revive
    - gosimple
    - govet
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - gofumpt
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - linters:
        - stylecheck
      text: "ST1001:"
    - path: _test\.go
      linters:
        - errcheck
        - funlen

service:
  golangci-lint-version: 1.51.x # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"