groups:
  - name: konsumer-alerts
    rules:
      - alert: ProcessedRetryMessageIncreasing
        expr: rate(kafka_konsumer_processed_retry_messages_total{job="konsumer"}[1m]) > 0.25
        for: 1m
        labels:
          severity: "error"
        annotations:
          summary: "Kafka Konsumer processed retry message increasing, current rate: {{ $value }}"
      - alert: ProcessedMessageDecreasing
        expr: rate(kafka_konsumer_processed_messages_total{job="konsumer"}[1m]) < 0.1
        for: 1m
        labels:
          severity: "critical"
        annotations:
          summary: "Kafka Konsumer processed message decreasing, current rate: {{ $value }}"
