global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "konsumer"
    static_configs:
      - targets: ["host.docker.internal:8090"]

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9090'
