version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./configs/zookeeper.sasl.jaas.config:/etc/kafka/zookeeper_server_jaas.conf
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/zookeeper_server_jaas.conf
        -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dzookeeper.allowSaslFailedClients=false
        -Dzookeeper.requireClientAuthScheme=sasl

  broker:
    image: confluentinc/cp-kafka
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "29093:29093"
    volumes:
      - ./configs/kafka.jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./configs/client.properties:/tmp/client.properties
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: 'test-writer-0:3:1,test-writer-1:3:1'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:SASL_PLAINTEXT,HOST:SASL_PLAINTEXT
      KAFKA_LISTENERS: BROKER://:9093,HOST://:29093
      KAFKA_ADVERTISED_LISTENERS: BROKER://broker:9093,HOST://localhost:29093
      KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_BROKER_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="broker" \
        password="broker" \
        user_broker="broker" \
        user_client="client-secret";
      KAFKA_LISTENER_NAME_HOST_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_HOST_PLAIN_SASL_JAAS_CONFIG: |
        org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="broker" \
        password="broker" \
        user_broker="broker" \
        user_client="client-secret";
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"

  kafka-ui:
    image: quay.io/cloudhut/kowl:master
    container_name: kafkaui
    hostname: kafkaui
    depends_on:
      - broker
    environment:
      KAFKA_BROKERS: broker:9093
      KAFKA_SASL_ENABLED: "true"
      KAFKA_SASL_USERNAME: client
      KAFKA_SASL_PASSWORD: client-secret
      KAFKA_SASL_MECHANISM: PLAIN
      KAFKA_RACKID: rack1
      KAFKA_CLIENTID: client
    ports:
      - "8080:8080"


  kafka-create-topics:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper
      - broker
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server broker:9093 --list --command-config /etc/kafka/client.properties

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server broker:9093 --create --if-not-exists --topic standard-topic --replication-factor 1 --partitions 1 --command-config /etc/kafka/client.properties
      kafka-topics --bootstrap-server broker:9093 --create --if-not-exists --topic retry-topic --replication-factor 1 --partitions 1 --command-config /etc/kafka/client.properties

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server broker:9093 --list --command-config /etc/kafka/client.properties
      "
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OPTS:
        -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
    volumes:
      - ./configs/client.properties:/etc/kafka/client.properties