{
 "title": "Kafka Konsumer Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kafka Konsumer Processed Messages Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_konsumer_processed_messages_total{job=\"konsumer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Konsumer Processed Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(sum(kafka_konsumer_processed_messages_total{job=\"konsumer\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Konsumer Processed Retry Messages Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kafka_konsumer_processed_retry_messages_total{job=\"konsumer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Konsumer Processed Retry Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(sum(kafka_konsumer_processed_retry_messages_total{job=\"konsumer\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}