name: 🔨IntegrationTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - uses: actions/checkout@v4
      - name: Start containers
        run: docker compose -f test/integration/docker-compose.yml up --wait --build --force-recreate --remove-orphans

      - uses: actions/checkout@v4
      - name: Integration Test
        run: go test -v test/integration/integration_test.go
        env:
          INPUT_PUBLISH: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}